[project]
name = "confit-factories"
version = "0.1.0"

description = "A collection of confit factories."
readme = "README.md"
authors = [{ name = "Basile Dura", email = "basile@bdura.me" }]
requires-python = ">=3.13"
dependencies = ["confit-lite"]

[project.entry-points.'confit']
factories = "confit_factories"

[tool.uv.sources]
confit-lite = { workspace = true }

[build-system]
requires = ["uv_build>=0.9.12,<0.10.0"]
build-backend = "uv_build"
